name: azureml-training
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - 'azureml-dataset-runtime[pandas,fuse]'
      - azureml-defaults==1.36.0
      - numpy
      - scikit-learn
      - tensorflow
      - opencv-python-headless==4.5.4.60