name: azureml-training
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - 'azureml-dataset-runtime[pandas,fuse]'
      - azureml-defaults==1.36.0
      - numpy==1.24.2
      - scikit-learn==1.0.1
      - tensorflow==2.7.0
      - opencv-python-headless==4.5.4.60